controller_list:
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - Neck_Hor_Rot_Joint
      - Neck_Fro_Rot_Joint
  - name: fake_monkey_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - L_Shoulder_Fro_Joint
      - L_Shoulder_Lat_Joint
      - L_Shoulder_Hor_Joint
      - L_Ellbow_Joint
      - L_Wrist_Joint
      - L_Hand_Joint
  - name: fake_monkey_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - R_Shoulder_Fro_Rot_Joint
      - R_Shoulder_Lat_Joint
      - R_Shoulder_Hor_Joint
      - R_Ellbow_Joint
      - R_Wrist_Joint
      - R_Hand_Joint
  - name: fake_monkey_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - L_Hand_Joint
  - name: fake_monkey_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - R_Hand_Joint
initial:  # Define initial robot poses per group
  - group: head
    pose: head_def
  - group: monkey_left_arm
    pose: left_arm_def
  - group: monkey_right_arm
    pose: right_arm_def